apiVersion: v1
kind: Secret
metadata:
  name: order-management-secrets
type: Opaque
data:
  # Base64 encoded values
  AUTH0_CLIENT_ID: your_base64_encoded_auth0_client_id
  AUTH0_CLIENT_SECRET: your_base64_encoded_auth0_client_secret
  AUTH0_DOMAIN: your_base64_encoded_auth0_domain
  AFRICAS_TALKING_USERNAME: your_base64_encoded_africastalking_username
  AFRICAS_TALKING_API_KEY: your_base64_encoded_africastalking_api_key
  POSTGRES_DB: your_base64_encoded_postgres_db_name
  POSTGRES_USER: your_base64_encoded_postgres_user
  POSTGRES_PASSWORD: your_base64_encoded_postgres_password